services:
  db:
    image: postgres:16
    container_name: epharm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: epharm
      POSTGRES_PASSWORD: epharm_password
      POSTGRES_DB: epharm
    ports:
      - "5432:5432"
    volumes:
      - epharm_data:/var/lib/postgresql/data

volumes:
  epharm_data:
